version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
install:
  - set QTDIR=C:\Qt\5.12.2\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
before_build:
- cmd: nuget restore & set PATH=%QTDIR%\bin;C:\Qt\5.12.2\msvc2017_64;C:\Qt\5.12.2\msvc2017_64\bin;%PATH%
build:
  project: matlab.sln
  verbosity: minimal
